apiVersion: v1
kind: ConfigMap
metadata:
  name: forja-config
  namespace: forja-staging
  labels:
    app.kubernetes.io/part-of: forja
data:
  ENV: staging
  LOG_LEVEL: info
  KAFKA_BROKERS: kafka.forja-staging.svc.cluster.local:9092
  MEILISEARCH_URL: http://meilisearch.forja-staging.svc.cluster.local:7700
  CLICKHOUSE_DSN: clickhouse://forja:forja@clickhouse.forja-staging.svc.cluster.local:9000/forja
  MINIO_ENDPOINT: minio.forja-staging.svc.cluster.local:9000
  MINIO_PUBLIC_BASE: https://media.forja.app
  MINIO_BUCKET: forja-staging
