apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forja-ingress
  namespace: forja-staging
  labels:
    app.kubernetes.io/part-of: forja
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - "*.forja.app"
        - api.forja.app
      secretName: forja-tls
  rules:
    - host: api.forja.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
    - host: "*.forja.app"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
